# ==========================================================
# Fichier render.yaml - La VRAIE Version Correcte
# ==========================================================

# On définit d'abord les bases de données
databases:
  - name: bdd-matieres # Nom de notre base de données
    databaseName: matieres_db # Nom réel de la BDD à l'intérieur du serveur
    user: api_user # Nom de l'utilisateur qui sera créé
    plan: free # Le plan gratuit

# Ensuite, on définit les services qui vont utiliser ces bases de données
services:
  # Notre application web FastAPI
  - type: web
    name: projet-api-matieres
    env: python
    plan: free
    # Commande pour installer les dépendances
    buildCommand: "pip install -r requirements.txt"
    # Commande pour démarrer le serveur de production
    startCommand: "gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker"
    # Définition des variables d'environnement
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DATABASE_URL
        # On récupère l'URL de connexion depuis la base de données définie ci-dessus
        fromDatabase:
          name: bdd-matieres
          property: connectionString