# ===============================================
# Fichier render.yaml CORRIGÉ et VÉRIFIÉ
# ===============================================

services:
  # 1. Notre Base de Données PostgreSQL
  - type: pserv
    name: bdd-matieres
    env: postgres
    plan: free
    postgresMajorVersion: 14
    # Les données de la BDD sont conservées même si le service redémarre
    volume:
      name: postgres-data
      mountPath: /var/lib/postgresql/data

  # 2. Notre Application Web FastAPI
  - type: web
    name: projet-api-matieres
    env: python
    plan: free
    # Commande pour construire le projet
    buildCommand: "pip install -r requirements.txt"
    # Commande pour démarrer le serveur (utilise notre script)
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11" # Le Python 3.13 n'est pas encore dispo, 3.11 est très sûr.
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: bdd-matieres
          property: connectionString